### ISSUE TITLE
The docs url in the README.md is broken

### ISSUE THREAD

**Issue by tylerasai** [ionos-cloud/sdk-ruby#2]
## Description

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/44843805/171774928-cf51edfd-45cf-4034-8a7d-c7adb06cc746.png">

this link on https://github.com/ionos-cloud/sdk-ruby/blob/master/README.md page is broken.

## Expected behavior

I believe it should direct to https://github.com/ionos-cloud/sdk-ruby/tree/master/docs

**Comment by rmocanu-ionos** [comment]
Hello, it was indeed broken, thank you for telling us. It is now fixed.
